### ISSUE TITLE
save/load state

### ISSUE THREAD

**Issue by AngelofMe** [libretro/virtualjaguar-libretro#76] opened 2022-07-19 12:15 UTC
IrataJaguar allow me to save and load states from slots. it's a part of Phoenix (a 3DO, Sega 8-bit, ColecoVision, Jaguar emulator) Android version
but I don't know why this emulator doesn't support Save States, Load States, State Slots
I didn't see these features from RetroArch since I download this emulator

**Comment by djipi** [comment] 2022-09-02 22:02
> but I don't know why this emulator doesn't support Save States, Load States, State Slots

Because someone must do it.
You can take a look at the patch described in https://atariage.com/forums/topic/243174-save-states-for-virtual-jaguar-patch/
And then try to integrate in the emulator.

**Comment by JoeMatt** [comment] 2022-11-21 01:57
I think I have code for this actually, that needs to be moved into `libretro.c`

This is how I'm doing it in Provenance in Obj-C and it seems to be working just fine for users and myself.

```objc
static void loadSaveFile(const char* path, int type) {
    FILE *file;
    
    file = fopen(path, "rb");
    if ( !file ) {
        return;
    }
    
    size_t size = retro_get_memory_size(type);
    void *data  = retro_get_memory_data(type);
    
    if (size == 0 || !data) {
        fclose(file);
        return;
    }
    
    int rc = fread(data, sizeof(uint8_t), size, file);
    if ( rc != size ) {
        DLOG(@"Couldn't load save file.");
    }
    
    DLOG(@"Loaded save file: %s", path);
    fclose(file);
}

static void writeSaveFile(const char* path, int type) {
    size_t size = retro_get_memory_size(type);
    void *data = retro_get_memory_data(type);
    
    if ( data && size > 0 ) {
        FILE *file = fopen(path, "wb");
        if ( file != NULL ) {
            DLOG(@"Saving state %s. Size: %d bytes.", path, (int)size);
            retro_serialize(data, size);
            if ( fwrite(data, sizeof(uint8_t), size, file) != size ) {
                DLOG(@"Did not save state properly.");
            }
            fclose(file);
        }
    }
}
```

**Comment by JoeMatt** [comment] 2022-11-23 21:42
Dupe of #8

Closing.

**Closed by JoeMatt** 2022-11-23 21:42 UTC

**Comment by djipi** [comment] 2022-11-25 13:09
For the record, it is not a dup.
The #8 is about eeprom / game save.
The discussed task is about save the console state.
